// ============ TRADUCTION DES TALENTS (ABILITIES) ============
// L'API Tyradex ne fournit les noms de talents qu'en français. Cette table
// (construite à partir des données publiques de PokeAPI/Bulbapedia, langues
// fr/en/ja) permet de les afficher aussi en anglais et en japonais. Elle est
// volontairement large (l'ensemble des talents connus, toutes générations)
// car on ne sait pas à l'avance lesquels apparaîtront dans les données.
// Si un talent n'est pas dans la table (nouveauté très récente), son nom
// français est affiché tel quel, comme avant.
const TALENT_NAME_TRANSLATIONS = {
  "Puanteur": { en: "Stench", jp: "あくしゅう" },
  "Crachin": { en: "Drizzle", jp: "あめふらし" },
  "Turbo": { en: "Speed Boost", jp: "かそく" },
  "Armurbaston": { en: "Battle Armor", jp: "カブトアーマー" },
  "Fermeté": { en: "Sturdy", jp: "がんじょう" },
  "Moiteur": { en: "Damp", jp: "しめりけ" },
  "Échauffement": { en: "Limber", jp: "じゅうなん" },
  "Voile Sable": { en: "Sand Veil", jp: "すながくれ" },
  "Statik": { en: "Static", jp: "せいでんき" },
  "Absorbe-Volt": { en: "Volt Absorb", jp: "ちくでん" },
  "Absorbe-Eau": { en: "Water Absorb", jp: "ちょすい" },
  "Benêt": { en: "Oblivious", jp: "どんかん" },
  "Ciel Gris": { en: "Cloud Nine", jp: "ノーてんき" },
  "Œil Composé": { en: "Compound Eyes", jp: "ふくがん" },
  "Insomnia": { en: "Insomnia", jp: "ふみん" },
  "Homochromie": { en: "Color Change", jp: "へんしょく" },
  "Vaccin": { en: "Immunity", jp: "めんえき" },
  "Torche": { en: "Flash Fire", jp: "もらいび" },
  "Écran Poudre": { en: "Shield Dust", jp: "りんぷん" },
  "Tempo Perso": { en: "Own Tempo", jp: "マイペース" },
  "Ventouse": { en: "Suction Cups", jp: "きゅうばん" },
  "Intimidation": { en: "Intimidate", jp: "いかく" },
  "Marque Ombre": { en: "Shadow Tag", jp: "かげふみ" },
  "Peau Dure": { en: "Rough Skin", jp: "さめはだ" },
  "Garde Mystik": { en: "Wonder Guard", jp: "ふしぎなまもり" },
  "Lévitation": { en: "Levitate", jp: "ふゆう" },
  "Pose Spore": { en: "Effect Spore", jp: "ほうし" },
  "Synchro": { en: "Synchronize", jp: "シンクロ" },
  "Corps Sain": { en: "Clear Body", jp: "クリアボディ" },
  "Médic Nature": { en: "Natural Cure", jp: "しぜんかいふく" },
  "Paratonnerre": { en: "Lightning Rod", jp: "ひらいしん" },
  "Sérénité": { en: "Serene Grace", jp: "てんのめぐみ" },
  "Glissade": { en: "Swift Swim", jp: "すいすい" },
  "Chlorophylle": { en: "Chlorophyll", jp: "ようりょくそ" },
  "Lumiattirance": { en: "Illuminate", jp: "はっこう" },
  "Calque": { en: "Trace", jp: "トレース" },
  "Coloforce": { en: "Huge Power", jp: "ちからもち" },
  "Point Poison": { en: "Poison Point", jp: "どくのトゲ" },
  "Attention": { en: "Inner Focus", jp: "せいしんりょく" },
  "Armumagma": { en: "Magma Armor", jp: "マグマのよろい" },
  "Ignifu-Voile": { en: "Water Veil", jp: "みずのベール" },
  "Magnépiège": { en: "Magnet Pull", jp: "じりょく" },
  "Anti-Bruit": { en: "Soundproof", jp: "ぼうおん" },
  "Cuvette": { en: "Rain Dish", jp: "あめうけざら" },
  "Sable Volant": { en: "Sand Stream", jp: "すなおこし" },
  "Pression": { en: "Pressure", jp: "プレッシャー" },
  "Isograisse": { en: "Thick Fat", jp: "あついしぼう" },
  "Matinal": { en: "Early Bird", jp: "はやおき" },
  "Corps Ardent": { en: "Flame Body", jp: "ほのおのからだ" },
  "Fuite": { en: "Run Away", jp: "にげあし" },
  "Regard Vif": { en: "Keen Eye", jp: "するどいめ" },
  "Hyper Cutter": { en: "Hyper Cutter", jp: "かいりきバサミ" },
  "Ramassage": { en: "Pickup", jp: "ものひろい" },
  "Absentéisme": { en: "Truant", jp: "なまけ" },
  "Agitation": { en: "Hustle", jp: "はりきり" },
  "Joli Sourire": { en: "Cute Charm", jp: "メロメロボディ" },
  "Plus": { en: "Plus", jp: "プラス" },
  "Moins": { en: "Minus", jp: "マイナス" },
  "Météo": { en: "Forecast", jp: "てんきや" },
  "Glu": { en: "Sticky Hold", jp: "ねんちゃく" },
  "Mue": { en: "Shed Skin", jp: "だっぴ" },
  "Cran": { en: "Guts", jp: "こんじょう" },
  "Écaille Spéciale": { en: "Marvel Scale", jp: "ふしぎなうろこ" },
  "Suintement": { en: "Liquid Ooze", jp: "ヘドロえき" },
  "Engrais": { en: "Overgrow", jp: "しんりょく" },
  "Brasier": { en: "Blaze", jp: "もうか" },
  "Torrent": { en: "Torrent", jp: "げきりゅう" },
  "Essaim": { en: "Swarm", jp: "むしのしらせ" },
  "Tête de Roc": { en: "Rock Head", jp: "いしあたま" },
  "Sécheresse": { en: "Drought", jp: "ひでり" },
  "Piège Sable": { en: "Arena Trap", jp: "ありじごく" },
  "Esprit Vital": { en: "Vital Spirit", jp: "やるき" },
  "Écran Fumée": { en: "White Smoke", jp: "しろいけむり" },
  "Force Pure": { en: "Pure Power", jp: "ヨガパワー" },
  "Coque Armure": { en: "Shell Armor", jp: "シェルアーマー" },
  "Air Lock": { en: "Air Lock", jp: "エアロック" },
  "Pieds Confus": { en: "Tangled Feet", jp: "ちどりあし" },
  "Motorisé": { en: "Motor Drive", jp: "でんきエンジン" },
  "Rivalité": { en: "Rivalry", jp: "とうそうしん" },
  "Impassible": { en: "Steadfast", jp: "ふくつのこころ" },
  "Rideau Neige": { en: "Snow Cloak", jp: "ゆきがくれ" },
  "Gloutonnerie": { en: "Gluttony", jp: "くいしんぼう" },
  "Colérique": { en: "Anger Point", jp: "いかりのつぼ" },
  "Délestage": { en: "Unburden", jp: "かるわざ" },
  "Ignifugé": { en: "Heatproof", jp: "たいねつ" },
  "Simple": { en: "Simple", jp: "たんじゅん" },
  "Peau Sèche": { en: "Dry Skin", jp: "かんそうはだ" },
  "Télécharge": { en: "Download", jp: "ダウンロード" },
  "Poing de Fer": { en: "Iron Fist", jp: "てつのこぶし" },
  "Soin Poison": { en: "Poison Heal", jp: "ポイズンヒール" },
  "Adaptabilité": { en: "Adaptability", jp: "てきおうりょく" },
  "Multi-Coups": { en: "Skill Link", jp: "スキルリンク" },
  "Hydratation": { en: "Hydration", jp: "うるおいボディ" },
  "Force Soleil": { en: "Solar Power", jp: "サンパワー" },
  "Pied Véloce": { en: "Quick Feet", jp: "はやあし" },
  "Normalise": { en: "Normalize", jp: "ノーマルスキン" },
  "Sniper": { en: "Sniper", jp: "スナイパー" },
  "Garde Magik": { en: "Magic Guard", jp: "マジックガード" },
  "Annule Garde": { en: "No Guard", jp: "ノーガード" },
  "Frein": { en: "Stall", jp: "あとだし" },
  "Technicien": { en: "Technician", jp: "テクニシャン" },
  "Feuille Garde": { en: "Leaf Guard", jp: "リーフガード" },
  "Maladresse": { en: "Klutz", jp: "ぶきよう" },
  "Brise Moule": { en: "Mold Breaker", jp: "かたやぶり" },
  "Chanceux": { en: "Super Luck", jp: "きょううん" },
  "Boom Final": { en: "Aftermath", jp: "ゆうばく" },
  "Anticipation": { en: "Anticipation", jp: "きけんよち" },
  "Prédiction": { en: "Forewarn", jp: "よちむ" },
  "Inconscient": { en: "Unaware", jp: "てんねん" },
  "Lentiteintée": { en: "Tinted Lens", jp: "いろめがね" },
  "Filtre": { en: "Filter", jp: "フィルター" },
  "Début Calme": { en: "Slow Start", jp: "スロースタート" },
  "Querelleur": { en: "Scrappy", jp: "きもったま" },
  "Lavabo": { en: "Storm Drain", jp: "よびみず" },
  "Corps Gel": { en: "Ice Body", jp: "アイスボディ" },
  "Solide Roc": { en: "Solid Rock", jp: "ハードロック" },
  "Alerte Neige": { en: "Snow Warning", jp: "ゆきふらし" },
  "Cherche Miel": { en: "Honey Gather", jp: "みつあつめ" },
  "Fouille": { en: "Frisk", jp: "おみとおし" },
  "Téméraire": { en: "Reckless", jp: "すてみ" },
  "Multi-Type": { en: "Multitype", jp: "マルチタイプ" },
  "Don Floral": { en: "Flower Gift", jp: "フラワーギフト" },
  "Mauvais Rêve": { en: "Bad Dreams", jp: "ナイトメア" },
  "Pickpocket": { en: "Pickpocket", jp: "わるいてぐせ" },
  "Sans Limite": { en: "Sheer Force", jp: "ちからずく" },
  "Contestation": { en: "Contrary", jp: "あまのじゃく" },
  "Tension": { en: "Unnerve", jp: "きんちょうかん" },
  "Acharné": { en: "Defiant", jp: "まけんき" },
  "Défaitiste": { en: "Defeatist", jp: "よわき" },
  "Corps Maudit": { en: "Cursed Body", jp: "のろわれボディ" },
  "Cœur Soin": { en: "Healer", jp: "いやしのこころ" },
  "Garde-Ami": { en: "Friend Guard", jp: "フレンドガード" },
  "Armurouillée": { en: "Weak Armor", jp: "くだけるよろい" },
  "Heavy Metal": { en: "Heavy Metal", jp: "ヘヴィメタル" },
  "Light Metal": { en: "Light Metal", jp: "ライトメタル" },
  "Multiécaille": { en: "Multiscale", jp: "マルチスケイル" },
  "Rage Poison": { en: "Toxic Boost", jp: "どくぼうそう" },
  "Rage Brûlure": { en: "Flare Boost", jp: "ねつぼうそう" },
  "Récolte": { en: "Harvest", jp: "しゅうかく" },
  "Télépathe": { en: "Telepathy", jp: "テレパシー" },
  "Lunatique": { en: "Moody", jp: "ムラっけ" },
  "Envelocape": { en: "Overcoat", jp: "ぼうじん" },
  "Toxitouche": { en: "Poison Touch", jp: "どくしゅ" },
  "Régé-Force": { en: "Regenerator", jp: "さいせいりょく" },
  "Cœur de Coq": { en: "Big Pecks", jp: "はとむね" },
  "Baigne Sable": { en: "Sand Rush", jp: "すなかき" },
  "Peau Miracle": { en: "Wonder Skin", jp: "ミラクルスキン" },
  "Analyste": { en: "Analytic", jp: "アナライズ" },
  "Illusion": { en: "Illusion", jp: "イリュージョン" },
  "Imposteur": { en: "Imposter", jp: "かわりもの" },
  "Infiltration": { en: "Infiltrator", jp: "すりぬけ" },
  "Momie": { en: "Mummy", jp: "ミイラ" },
  "Impudence": { en: "Moxie", jp: "じしんかじょう" },
  "Cœur Noble": { en: "Justified", jp: "せいぎのこころ" },
  "Phobique": { en: "Rattled", jp: "びびり" },
  "Miroir Magik": { en: "Magic Bounce", jp: "マジックミラー" },
  "Herbivore": { en: "Sap Sipper", jp: "そうしょく" },
  "Farceur": { en: "Prankster", jp: "いたずらごころ" },
  "Force Sable": { en: "Sand Force", jp: "すなのちから" },
  "Épine de Fer": { en: "Iron Barbs", jp: "てつのトゲ" },
  "Mode Transe": { en: "Zen Mode", jp: "ダルマモード" },
  "Victorieux": { en: "Victory Star", jp: "しょうりのほし" },
  "Turbo Brasier": { en: "Turboblaze", jp: "ターボブレイズ" },
  "Téra-Voltage": { en: "Teravolt", jp: "テラボルテージ" },
  "Aroma-Voile": { en: "Aroma Veil", jp: "アロマベール" },
  "Flora-Voile": { en: "Flower Veil", jp: "フラワーベール" },
  "Bajoues": { en: "Cheek Pouch", jp: "ほおぶくろ" },
  "Protéen": { en: "Protean", jp: "へんげんじざい" },
  "Toison Épaisse": { en: "Fur Coat", jp: "ファーコート" },
  "Magicien": { en: "Magician", jp: "マジシャン" },
  "Pare-Balles": { en: "Bulletproof", jp: "ぼうだん" },
  "Battant": { en: "Competitive", jp: "かちき" },
  "Prognathe": { en: "Strong Jaw", jp: "がんじょうあご" },
  "Peau Gelée": { en: "Refrigerate", jp: "フリーズスキン" },
  "Gluco-Voile": { en: "Sweet Veil", jp: "スイートベール" },
  "Déclic Tactique": { en: "Stance Change", jp: "バトルスイッチ" },
  "Ailes Bourrasque": { en: "Gale Wings", jp: "はやてのつばさ" },
  "Méga Blaster": { en: "Mega Launcher", jp: "メガランチャー" },
  "Toison Herbue": { en: "Grass Pelt", jp: "くさのけがわ" },
  "Symbiose": { en: "Symbiosis", jp: "きょうせい" },
  "Griffe Dure": { en: "Tough Claws", jp: "かたいツメ" },
  "Peau Féérique": { en: "Pixilate", jp: "フェアリースキン" },
  "Poisseux": { en: "Gooey", jp: "ぬめぬめ" },
  "Peau Céleste": { en: "Aerilate", jp: "スカイスキン" },
  "Amour Filial": { en: "Parental Bond", jp: "おやこあい" },
  "Aura Ténébreuse": { en: "Dark Aura", jp: "ダークオーラ" },
  "Aura Féérique": { en: "Fairy Aura", jp: "フェアリーオーラ" },
  "Aura Inversée": { en: "Aura Break", jp: "オーラブレイク" },
  "Mer Primaire": { en: "Primordial Sea", jp: "はじまりのうみ" },
  "Terre Finale": { en: "Desolate Land", jp: "おわりのだいち" },
  "Souffle Delta": { en: "Delta Stream", jp: "デルタストリーム" },
  "Endurance": { en: "Stamina", jp: "じきゅうりょく" },
  "Escampette": { en: "Wimp Out", jp: "にげごし" },
  "Repli Tactique": { en: "Emergency Exit", jp: "ききかいひ" },
  "Sable Humide": { en: "Water Compaction", jp: "みずがため" },
  "Cruauté": { en: "Merciless", jp: "ひとでなし" },
  "Bouclier-Carcan": { en: "Shields Down", jp: "リミットシールド" },
  "Filature": { en: "Stakeout", jp: "はりこみ" },
  "Aquabulle": { en: "Water Bubble", jp: "すいほう" },
  "Expert Acier": { en: "Steelworker", jp: "はがねつかい" },
  "Folle Furie": { en: "Berserk", jp: "ぎゃくじょう" },
  "Chasse-Neige": { en: "Slush Rush", jp: "ゆきかき" },
  "Longue Portée": { en: "Long Reach", jp: "えんかく" },
  "Hydrata-Son": { en: "Liquid Voice", jp: "うるおいボイス" },
  "Prioguérison": { en: "Triage", jp: "ヒーリングシフト" },
  "Peau Électrique": { en: "Galvanize", jp: "エレキスキン" },
  "Surf Caudal": { en: "Surge Surfer", jp: "サーフテール" },
  "Banc": { en: "Schooling", jp: "ぎょぐん" },
  "Fantômasque": { en: "Disguise", jp: "ばけのかわ" },
  "Synergie": { en: "Battle Bond", jp: "きずなへんげ" },
  "Rassemblement": { en: "Power Construct", jp: "スワームチェンジ" },
  "Corrosion": { en: "Corrosion", jp: "ふしょく" },
  "Hypersommeil": { en: "Comatose", jp: "ぜったいねむり" },
  "Prestance Royale": { en: "Queenly Majesty", jp: "じょおうのいげん" },
  "Expuls'Organes": { en: "Innards Out", jp: "とびだすなかみ" },
  "Danseuse": { en: "Dancer", jp: "おどりこ" },
  "Batterie": { en: "Battery", jp: "バッテリー" },
  "Boule de Poils": { en: "Fluffy", jp: "もふもふ" },
  "Corps Coloré": { en: "Dazzling", jp: "ビビッドボディ" },
  "Animacœur": { en: "Soul-Heart", jp: "ソウルハート" },
  "Mèche Rebelle": { en: "Tangling Hair", jp: "カーリーヘアー" },
  "Receveur": { en: "Receiver", jp: "レシーバー" },
  "Osmose": { en: "Power of Alchemy", jp: "かがくのちから" },
  "Boost Chimère": { en: "Beast Boost", jp: "ビーストブースト" },
  "Système Alpha": { en: "RKS System", jp: "ＡＲシステム" },
  "Créa-Élec": { en: "Electric Surge", jp: "エレキメイカー" },
  "Créa-Psy": { en: "Psychic Surge", jp: "サイコメイカー" },
  "Créa-Brume": { en: "Misty Surge", jp: "ミストメイカー" },
  "Créa-Herbe": { en: "Grassy Surge", jp: "グラスメイカー" },
  "Métallo-Garde": { en: "Full Metal Body", jp: "メタルプロテクト" },
  "Spectro-Bouclier": { en: "Shadow Shield", jp: "ファントムガード" },
  "Prisme-Armure": { en: "Prism Armor", jp: "プリズムアーマー" },
  "Cérébro-Force": { en: "Neuroforce", jp: "ブレインフォース" },
  "Lame Indomptable": { en: "Intrepid Sword", jp: "ふとうのけん" },
  "Égide Inflexible": { en: "Dauntless Shield", jp: "ふくつのたて" },
  "Libéro": { en: "Libero", jp: "リベロ" },
  "Ramasse Ball": { en: "Ball Fetch", jp: "たまひろい" },
  "Effilochage": { en: "Cotton Down", jp: "わたげ" },
  "Propulseur": { en: "Propeller Tail", jp: "スクリューおびれ" },
  "Armure Miroir": { en: "Mirror Armor", jp: "ミラーアーマー" },
  "Dégobage": { en: "Gulp Missile", jp: "うのミサイル" },
  "Nerfs d'Acier": { en: "Stalwart", jp: "すじがねいり" },
  "Turbine": { en: "Steam Engine", jp: "じょうききかん" },
  "Punk Rock": { en: "Punk Rock", jp: "パンクロック" },
  "Expul'Sable": { en: "Sand Spit", jp: "すなはき" },
  "Écailles Glacées": { en: "Ice Scales", jp: "こおりのりんぷん" },
  "Mûrissement": { en: "Ripen", jp: "じゅくせい" },
  "Tête de Gel": { en: "Ice Face", jp: "アイスフェイス" },
  "Cercle d'Énergie": { en: "Power Spot", jp: "パワースポット" },
  "Mimétisme": { en: "Mimicry", jp: "ぎたい" },
  "Brise-Barrière": { en: "Screen Cleaner", jp: "バリアフリー" },
  "Boost Acier": { en: "Steely Spirit", jp: "はがねのせいしん" },
  "Corps Condamné": { en: "Perish Body", jp: "ほろびのボディ" },
  "Âme Vagabonde": { en: "Wandering Spirit", jp: "さまようたましい" },
  "Entêtement": { en: "Gorilla Tactics", jp: "ごりむちゅう" },
  "Gaz Inhibiteur": { en: "Neutralizing Gas", jp: "かがくへんかガス" },
  "Voile Pastel": { en: "Pastel Veil", jp: "パステルベール" },
  "Déclic Fringale": { en: "Hunger Switch", jp: "はらぺこスイッチ" },
  "Tir Vif": { en: "Quick Draw", jp: "クイックドロウ" },
  "Poing Invisible": { en: "Unseen Fist", jp: "ふかしのこぶし" },
  "Breuvage Suspect": { en: "Curious Medicine", jp: "きみょうなくすり" },
  "Transistor": { en: "Transistor", jp: "トランジスタ" },
  "Dent de Dragon": { en: "Dragon's Maw", jp: "りゅうのあぎと" },
  "Blanche Ruade": { en: "Chilling Neigh", jp: "しろのいななき" },
  "Sombre Ruade": { en: "Grim Neigh", jp: "くろのいななき" },
  "Osmose Équine": { en: "As One", jp: "じんばいったい" },
  "Odeur Tenace": { en: "Lingering Aroma", jp: "とれないにおい" },
  "Semencier": { en: "Seed Sower", jp: "こぼれダネ" },
  "Thermodynamique": { en: "Thermal Exchange", jp: "ねつこうかん" },
  "Courroupace": { en: "Anger Shell", jp: "いかりのこうら" },
  "Sel Purificateur": { en: "Purifying Salt", jp: "きよめのしお" },
  "Bien Cuit": { en: "Well-Baked Body", jp: "こんがりボディ" },
  "Aéroporté": { en: "Wind Rider", jp: "かぜのり" },
  "Chien de Garde": { en: "Guard Dog", jp: "ばんけん" },
  "Porte-Roche": { en: "Rocky Payload", jp: "いわはこび" },
  "Turbine Éolienne": { en: "Wind Power", jp: "ふうりょくでんき" },
  "Supermutation": { en: "Zero to Hero", jp: "マイティチェンジ" },
  "Commandant": { en: "Commander", jp: "しれいとう" },
  "Grecharge": { en: "Electromorphosis", jp: "でんきにかえる" },
  "Paléosynthèse": { en: "Protosynthesis", jp: "こだいかっせい" },
  "Charge Quantique": { en: "Quark Drive", jp: "クォークチャージ" },
  "Corps en Or": { en: "Good as Gold", jp: "おうごんのからだ" },
  "Urne du Fléau": { en: "Vessel of Ruin", jp: "わざわいのうつわ" },
  "Épée du Fléau": { en: "Sword of Ruin", jp: "わざわいのつるぎ" },
  "Bois du Fléau": { en: "Tablets of Ruin", jp: "わざわいのおふだ" },
  "Perles du Fléau": { en: "Beads of Ruin", jp: "わざわいのたま" },
  "Pouls Orichalque": { en: "Orichalcum Pulse", jp: "ひひいろのこどう" },
  "Moteur à Hadrons": { en: "Hadron Engine", jp: "ハドロンエンジン" },
  "Opportuniste": { en: "Opportunist", jp: "びんじょう" },
  "Ruminant": { en: "Cud Chew", jp: "はんすう" },
  "Incisif": { en: "Sharpness", jp: "きれあじ" },
  "Général Suprême": { en: "Supreme Overlord", jp: "そうだいしょう" },
  "Collab": { en: "Costar", jp: "きょうえん" },
  "Dépôt Toxique": { en: "Toxic Debris", jp: "どくげしょう" },
  "Armure Caudale": { en: "Armor Tail", jp: "テイルアーマー" },
  "Absorbe-Terre": { en: "Earth Eater", jp: "どしょく" },
  "Force Fongique": { en: "Mycelium Might", jp: "きんしのちから" },
  "Œil Révélateur": { en: "Mind's Eye", jp: "しんがん" },
  "Nectar Mielleux": { en: "Supersweet Syrup", jp: "かんろなミツ" },
  "Aux Petits Soins": { en: "Hospitality", jp: "おもてなし" },
  "Chaîne Toxique": { en: "Toxic Chain", jp: "どくのくさり" },
  "Force Mémorielle": { en: "Embody Aspect", jp: "おもかげやどし" },
};

// Recherche insensible au style d'apostrophe : Tyradex et la table ci-dessus
// n'utilisent pas forcément le même caractère (' droit vs ' typographique),
// on normalise donc les deux côtés avant de comparer.
function normalizeApostrophes(str) {
  return str.replace(/[’‘]/g, "'");
}

const TALENT_LOOKUP = new Map(
  Object.entries(TALENT_NAME_TRANSLATIONS).map(([fr, tr]) => [normalizeApostrophes(fr), tr])
);

// Traduit un nom de talent français vers la langue actuelle. Repli sur le
// nom français d'origine si le talent est absent de la table (nouveauté non
// répertoriée) ou si la langue actuelle est le français.
function talentDisplayName(frenchName) {
  if (!frenchName) return frenchName;
  if (CURRENT_LANG === "fr") return frenchName;
  const entry = TALENT_LOOKUP.get(normalizeApostrophes(frenchName));
  if (!entry) return frenchName;
  return entry[CURRENT_LANG] || frenchName;
}
